line:
  client:
    oauth:
      url:
        verify: https://api.line.me/oauth2/v2.1/verify
    message:
      url:
        push: https://api.line.me/v2/bot/message/push
google:
  sheet:
    oauth: https://www.googleapis.com/auth/spreadsheets
db:
  postgres:
    host: localhost:5432
    port: 5432
    username: root
    password: password
    name: avah